@RequestFlow.Api_HostAddress = http://localhost:5285
POST https://localhost:7157/api/tickets
Content-Type: application/json

{
  "title": "VPN access required",
  "description": "I need VPN access for remote work.",
  "priority": "Medium"
}